apiVersion: v1
kind: Service
metadata:
  name: node-pinger
  namespace: kube-system
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: node-pinger
  ports:
    - name: metrics
      port: 9095
      targetPort: metrics
